'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProdeskNet.BD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=LTELMXMH\SQL2012;Initial Catalog=Procotiza_Prod;User ID=sa;Password=telepro.
        '''</summary>
        Friend ReadOnly Property BDProcotiza() As String
            Get
                Return ResourceManager.GetString("BDProcotiza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=LTELMXMH\SQL2012;Initial Catalog=ProdeskNet;User ID=sa;Password=telepro.
        '''</summary>
        Friend ReadOnly Property BDProdeskNet() As String
            Get
                Return ResourceManager.GetString("BDProdeskNet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=LTELMXMH\SQL2012;Initial Catalog=ProdeskNet;User ID=sa;Password=telepro.
        '''</summary>
        Friend ReadOnly Property Otra1() As String
            Get
                Return ResourceManager.GetString("Otra1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=LTELMXMH\SQL2012;Initial Catalog=ProdeskNet;User ID=sa;Password=telepro.
        '''</summary>
        Friend ReadOnly Property Otra2() As String
            Get
                Return ResourceManager.GetString("Otra2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=LTELMXMH\SQL2012;Initial Catalog=Procotiza_Prod;User ID=sa;Password=telepro.
        '''</summary>
        Friend ReadOnly Property OtraPC1() As String
            Get
                Return ResourceManager.GetString("OtraPC1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=LTELMXMH\SQL2012;Initial Catalog=Procotiza_Prod;User ID=sa;Password=telepro.
        '''</summary>
        Friend ReadOnly Property OtraPC2() As String
            Get
                Return ResourceManager.GetString("OtraPC2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
