'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CaratulaAutorizacion

    '''<summary>
    '''tags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tags As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnBuscarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarCliente As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblsolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsolicitud As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnombresol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnombresol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblfechasol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfechasol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumCotiza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumCotiza As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grvCaratula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvCaratula As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbldicPre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldicPre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcondi1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcondi1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCondi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCondi2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCondi3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCondi3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCondi4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCondi4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imagSolicita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imagSolicita As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblbc_coa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbc_coa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgCoacre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCoacre As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblicc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblicc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblicc_coa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblicc_coa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblresulscore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblresulscore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnomCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnomCom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRFC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltelpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltelpar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltelmov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltelmov As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcorreoe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcorreoe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbledad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbledad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldomi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldomi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcolonia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcolonia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldelega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldelega As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblestado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblestado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblciudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblciudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsexo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsexo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblfechana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfechana As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnaciona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnaciona As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcrup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcrup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblestadocivil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblestadocivil As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblvive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpropiedadasu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpropiedadasu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcompania control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcompania As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpuesto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldepartamen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldepartamen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltelemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltelemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblextemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblextemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblanoantiguedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblanoantiguedad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsuelmensu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsuelmensu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDomEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDomEmp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcpemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcpemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcoloniemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcoloniemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldelegaemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldelegaemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblestadoemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblestadoemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblciudademp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblciudademp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnombreComcoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnombreComcoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrfccoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrfccoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltelparcoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltelparcoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltelemovicoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltelemovicoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcorroelecoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcorroelecoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbledadcoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbledadcoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldomicicoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldomicicoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcpcoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcpcoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcoloniacoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcoloniacoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldelegacoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldelegacoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblestadocoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblestadocoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblciudadcoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblciudadcoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsexocoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsexocoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblfechanacimicoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfechanacimicoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnacionalicoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnacionalicoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcrpcoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcrpcoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblestadocivicoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblestadocivicoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblvivencoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvivencoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpropiedadcoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpropiedadcoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grvDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvDocumento As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hndtexto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hndtexto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblNomUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As ProdeskNet.Home
        Get
            Return CType(MyBase.Master, ProdeskNet.Home)
        End Get
    End Property
End Class
