'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class consultaReglasNegocio

    '''<summary>
    '''txtRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCondicionNva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCondicionNva As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValorNva1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorNva1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValorNva2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorNva2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlRechazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRechazo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As ProdeskNet.Home
        Get
            Return CType(MyBase.Master, ProdeskNet.Home)
        End Get
    End Property
End Class
