<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/aspx/Home.Master" CodeFile="SignalR.aspx.vb" Inherits="SignalR" %>
<%--<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>--%>
<%@ MasterType VirtualPath="~/aspx/home.master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphPantallas" runat="server">

    <!--  BUG-PD-364 GVARGAS 21/02/2018 Correccion panel avoid Ajax Tool Kit-->

     <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src = "../js/json2.js"></script>

    <script src= "../Scripts/jquery-1.6.4.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-1.1.2.js"></script>
    <script src = "../js/jquery.webticker.js"></script>
    
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="<%= ResolveUrl("~/signalr/hubs") %>" type="text/javascript"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        $(function () {            
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val($('[id$=hdUsuario]').val());         //prompt('Enter your name:', '')
            // Set initial focus to message input box.  
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();
                });
            });
        });
    </script>


    <div class="divAdminCatTitulo">
            <table>
                <tr>
                    <td class="tituloConsul">SignalR Simple Chat</td>
                </tr>
            </table>
        </div>
    <div class="divAdminCatCuerpo">
            <div class="container">
            <input type="text" id="message" />
            <input type="button" id="sendmessage" value="Send" />
            <input type="hidden" id="displayname" />
            <ul id="discussion">
            </ul>
        </div>    
        <asp:HiddenField ID = "hdUsuario" runat = "server" />
    </div>
</asp:Content>