CREATE PROCEDURE get_Detail_Contract_CI_SP
	@CTO_FL_CVE VARCHAR(20),
	@NOMBRE AS VARCHAR(MAX)
AS
BEGIN
    --BBVA-P-423 RQ-MN2-1 GVARGAS 07/09/2017 CI Precalificaciòn

	--EXEC get_Detail_Contract_CI_SP '00742224559600045786', 'FRANCISCO ARIEL VILLAVICENCIO ZAFRA'
	--EXEC get_Detail_Contract_CI_SP '00742224559600040000', 'FRANCISCO ARIEL VILLAVICENCIO ZAFRA'
	--EXEC get_Detail_Contract_CI_SP '00742224559600045786', 'FRANCISCO ARIEL VILLAVICENCIO ZAFRAA'

	DECLARE @CTO_CI VARCHAR(20) = ( SELECT TOP 1 CTO_FL_CVE FROM PDK_TAB_SECCION_CERO WHERE CTO_FL_CVE = @CTO_FL_CVE ORDER BY PDK_ID_SECCCERO DESC )

	IF @CTO_CI IS NULL
	BEGIN
		SELECT 'El contrato CI no existe.' AS MSG
	END
	ELSE
	BEGIN
		DECLARE @PDK_ID_SECCCERO VARCHAR(10) = ( SELECT TOP 1 PDK_ID_SECCCERO FROM PDK_TAB_SECCION_CERO WHERE CTO_FL_CVE = @CTO_CI ORDER BY PDK_ID_SECCCERO DESC )
		DECLARE @NOMBRE_ VARCHAR(MAX) = ( SELECT NOMBRE_SOLICI FROM PDK_TAB_DATOS_SOLICITANTE WHERE PDK_ID_SECCCERO = @PDK_ID_SECCCERO )

		IF @NOMBRE_ <> @NOMBRE
		BEGIN
			SELECT 'El nombre de la solicitud no coincide con el nombre del contrato.' AS MSG
		END
		ELSE
		BEGIN
			DECLARE @ID_COTIZACION VARCHAR(10) = ( SELECT ID_COTIZACION FROM PDK_TAB_SECCION_CERO WHERE PDK_ID_SECCCERO = @PDK_ID_SECCCERO ) 
			DECLARE @PLAZO INT = ( SELECT VALOR_PLAZO FROM bmnpad01..COTIZACIONES WHERE ID_COTIZACION = @ID_COTIZACION )
			DECLARE @FEC_PAGO DATE = ( SELECT FEC_PAGO FROM bmnpad01..TABLAAMORTIZA WHERE ID_COTIZACION = @ID_COTIZACION AND TIPO_TABLA = 1 AND NO_PAGO = @PLAZO )

			IF CONVERT(char(10), @FEC_PAGO, 126) > CONVERT(char(10), GetDate(), 126)
			BEGIN
				SELECT 'OK' AS MSG
			END
			ELSE
			BEGIN
				SELECT 'Fecha de Contrato no valida.' AS MSG
			END			
		END
	END
END