CREATE PROCEDURE get_InfoCI_SP
	@PDK_ID_SECCCERO INT
AS
BEGIN
    --BBVA-P-423 RQ-MN2-1 GVARGAS 07/09/2017 CI Precalificaciòn

	--EXEC get_InfoCI_SP 3590
	--EXEC get_InfoCI_SP 1654654
	--EXEC get_InfoCI_SP 1

	DECLARE @CI VARCHAR(2) = ( SELECT TOP 1 RENOVACION_CI FROM PDK_TAB_DATOS_SOLICITANTE WHERE PDK_ID_SECCCERO = @PDK_ID_SECCCERO ORDER BY PDK_ID_SECCCERO DESC )
	DECLARE @INE VARCHAR(2) = ( SELECT TOP 1 AUTORIZO_INE FROM PDK_TAB_DATOS_SOLICITANTE WHERE PDK_ID_SECCCERO = @PDK_ID_SECCCERO ORDER BY PDK_ID_SECCCERO DESC )

	SELECT CASE 
			   WHEN ISNULL(@CI, 'NO') = 'SI' THEN '1'
			   ELSE '0'
		   END AS CI,
		   CASE
		       WHEN ISNULL(@INE, 'NO') = 'SI' THEN '1'
			   ELSE '0'
		   END AS INE
END